services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Berlin
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./home-assistant/config:/config
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
